// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLtP-r7P2nedEaHtVX2rnFZh1H-13DDY',
    appId: '1:1076337604644:web:c4d8d0ca9ad2ac52e780b1',
    messagingSenderId: '1076337604644',
    projectId: 'cinema-tickets-web-app',
    databaseURL: 'https://your-database-id.firebasedatabase.app', // IMPORTANT!
    authDomain: 'cinema-tickets-web-app.firebaseapp.com',
    storageBucket: 'cinema-tickets-web-app.appspot.com',
    measurementId: 'G-FQFJ2D61PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT55XMJgeIA4ffNu5oD295ytV4jP-kK5U',
    appId: '1:1076337604644:android:665c7391f6c6c530e780b1',
    messagingSenderId: '1076337604644',
    projectId: 'cinema-tickets-web-app',
    storageBucket: 'cinema-tickets-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jP6j57NOBs8g2q0yYzek3JnlSjuMl0o',
    appId: '1:1076337604644:ios:7e5d3f502d6f7e63e780b1',
    messagingSenderId: '1076337604644',
    projectId: 'cinema-tickets-web-app',
    storageBucket: 'cinema-tickets-web-app.appspot.com',
    iosBundleId: 'com.example.cinemaTicketsWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jP6j57NOBs8g2q0yYzek3JnlSjuMl0o',
    appId: '1:1076337604644:ios:7e5d3f502d6f7e63e780b1',
    messagingSenderId: '1076337604644',
    projectId: 'cinema-tickets-web-app',
    storageBucket: 'cinema-tickets-web-app.appspot.com',
    iosBundleId: 'com.example.cinemaTicketsWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhLtP-r7P2nedEaHtVX2rnFZh1H-13DDY',
    appId: '1:1076337604644:web:c6aa00f373c7430be780b1',
    messagingSenderId: '1076337604644',
    projectId: 'cinema-tickets-web-app',
    authDomain: 'cinema-tickets-web-app.firebaseapp.com',
    storageBucket: 'cinema-tickets-web-app.appspot.com',
    measurementId: 'G-G3Y23MWKQL',
  );

}